name: Build and Run Docker Container
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: false
        tags: my-docker-registry/my-image-name:${{ github.sha }}

    - name: Run Docker container
      run: |
        docker run -p 8000:8000 my-docker-registry/my-image-name:${{ github.sha }}

    - name: Tear down Docker container
      run: |
        docker ps -a --filter "ancestor=my-docker-registry/my-image-name:${{ github.sha }}" -q | xargs -r docker stop
